name: Docker Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        pip install flake8 pytest pytest-cov
        pip install coverage
    - name: Lint Python (flake8)
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Run tests with coverage
      run: |
        export COVERAGE_PROCESS_START=.coveragerc
        pytest --cov=python-image/tests/ --cov-fail-under=80